---
# My first playbook
- name: simple playbook
  hosts: node1.example.com
  user: user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: create readme file
    copy:
      content: "welcome to my ftp server"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
...
